sudo: false

language: cpp
compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls

script:
  - make
  - make test
  - ./bin/server_tests

after_success:
  - coveralls

notifications:
  email: false
